# Generated by Django 4.2.11 on 2024-05-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_address_remove_profile_pincode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="pincode",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
