# Generated by Django 4.2.11 on 2024-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_address_profile_pincode_alter_profile_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pincode",
            field=models.CharField(max_length=7),
        ),
    ]
