# Generated by Django 4.2.11 on 2024-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(max_length=20),
        ),
    ]
