# Generated by Django 4.2.11 on 2024-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_address_alter_profile_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="addresses",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pincode",
            field=models.CharField(default="", max_length=7),
        ),
    ]
