# Generated by Django 4.2.11 on 2024-05-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_quantity"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_name",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
