# Generated by Django 4.2.11 on 2024-05-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_product_name_order_status_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
