# Generated by Django 4.2.11 on 2024-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_transit", "In Transit"),
                    ("processing", "Processing"),
                    ("delivered", "Delivered"),
                ],
                default="in_transit",
                max_length=20,
            ),
        ),
    ]
