# Generated by Django 4.2.11 on 2024-05-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
